### ISSUE TITLE
Kernel Restart Due to Missing libcudnn_ops_infer.so.8 on Google Colab

### ISSUE THREAD

**Issue by shkstar** [SYSTRAN/faster-whisper#1236]
I am running faster-whisper on Google Colab with CTranslate2==4.4.0 and CUDA-enabled PyTorch, but I am encountering kernel restarts due to a missing cuDNN library (libcudnn_ops_infer.so.8). Despite Colab having pre-installed CUDA and cuDNN, it seems this specific library is unavailable.

When I attempt to run my transcription workflow, I get the following error, followed by an automatic kernel restart:

Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory

After this warning, the kernel restarts with:

WARNING:root:kernel 4d7edf90-1ad4-411f-80d8-1f5bbde0ac17 restarted
INFO KernelRestarter: restarting kernel (1/5), keep random ports

**Comment by Purfview** [comment]
Last week they switched from cudnn v8 to cudnn v9.
Try CTranslate2==4.5.0 or install cudnn v8.

**Comment by shkstar** [comment]
Thank you, it works.

**Comment by iamashwin99** [comment]
I confirm that `pip install CTranslate2==4.5.0` works on colab.

Side note: for those using whisperX,  `whisperX==3.3.1` conflicts with  `CTranslate2==4.5.0`, current work around is to first install whisperX and then the CTranslate2 in a separate command

**Comment by kacpersh** [comment]
Does anyone have a different workaround? Installing CTranslate2==4.5.0 in Colab doesn't solve the problem.

**Comment by ptn24** [comment]
Nod. ctranslate2 does not work for me, but this does,

> It worked if I add [!apt-get install libcudnn8 libcudnn8-dev]
