### ISSUE TITLE
CUDA version problem in container

### ISSUE THREAD

**Issue by gyurobenjamin** [SYSTRAN/faster-whisper#1259]
I'm running the linuxserver/faster-whisper:gpu container within my k8s cluster.
Container runtime is nvidia, GPU is correctly attached.

Error:
`RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version`

Driver information on the host:
` NVIDIA-SMI 550.144.03             Driver Version: 550.144.03     CUDA Version: 12.4 `

**Comment by lord0gnome** [comment]
I have the same issue:
`| NVIDIA-SMI 570.124.04             Driver Version: 570.124.04     CUDA Version: 12.8     |`
I updated cuda and my display drivers from version 550~ and cuda 12.4 and I still have the same error.

**Comment by MahmoudAshraf97** [comment]
What GPU are you using?

**Comment by lord0gnome** [comment]
I am using an A2000, but it turns out this had nothing to do with it, the graphics card was not correctly attached in my case. I was using podman play kube and didn't configure it properly.

**Comment by gyurobenjamin** [comment]
> What GPU are you using?

RTX 3090 FE

**Comment by kds69** [comment]
same here
RTX 3090 MSI

**Comment by gyurobenjamin** [comment]
> same here RTX 3090 MSI

This worked for me: https://github.com/SYSTRAN/faster-whisper/issues/1259#issuecomment-2692294904

Unsure why it requires these requests. Other services can access it without it.
