### ISSUE TITLE
Library libcublas.so.12 is not found

### ISSUE THREAD

**Issue by Xiaomingpapapa** [SYSTRAN/faster-whisper#717]
upgrade faster-whisper version 0.10.0 -> 1.0.0
and meet the error: Library libcublas.so.12 is not found or cannot be loaded

operation system version: centos_7_9_x64
cuda version:  12.2

anyone else had the same problem?

**Comment by tuotuoshao** [comment]
I meet the same error. But my cuda version is 11.8 via command nvcc -V. So why  faster-whisper use cuda12? I can also get cuda version 12.2 via nvidia-smi, but as i known it's the driver version which means the latest cuda runtime version support.

**Comment by minhthuc2502** [comment]
From faster-whisper v1.0.0, it is compatible with only CUDA 12. See https://github.com/SYSTRAN/faster-whisper/releases/tag/v1.0.0

**Comment by minhthuc2502** [comment]
From faster-whisper 1.0.0, it requires CUDA 12 as the description [here](https://github.com/SYSTRAN/faster-whisper/releases/tag/v1.0.0) . You need to install CUDA runtime version 12.* . It is no longer compatible with CUDA 11.* .

**Comment by Oheed911** [comment]
`# Use an official Python runtime as a parent image
FROM python:3.8

# Add the NVIDIA key for CUDA 12 repositories
RUN curl "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb" -o cuda.deb && \
  dpkg -i cuda.deb && rm cuda.deb

# Install CUDA 12 runtime and development packages along with libcudnn and libcublas
RUN apt-get update -y && \
  apt-get install -y --no-install-recommends \
  cuda-cudart-12-0 cuda-nvcc-12-0 cuda-nvrtc-12-0 \
  libcudnn8 libcublas-12-0 && \
  rm -rf /var/lib/apt/lists/*

# Note: libcudnn version is not specified; adjust if necessary for specific version compatibility with CUDA 12

# Install python3, pip, and ffmpeg
RUN apt-get update && apt-get install -y python3 python3-pip libsndfile1 ffmpeg

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and the script to the container
COPY ./src /app

# Install Python dependencies
RUN pip3 install --no-cache-dir -r requirements.txt
`


above is my docker file, that resolved this issue.

**Comment by grzegorz700** [comment]
@minhthuc2502 Please refer to the right place where it mentions the requirements of cuda 12, if it exists. I understand that the release information only added support for Cuda 12. And still, in the README, there is nothing about stopping support for CUDA 11.* 

So this version (1.0.x) must be fixed to properly use cuda 11.8...

**Comment by minhthuc2502** [comment]
You can see it in this [release note](https://github.com/OpenNMT/CTranslate2/releases/tag/v4.0.0) in Ctranslate2. It needs to be more clear in the notes but it was emphasized that this is the major version of Ctranslate2 because of the breaking change when going up to CUDA 12.*.

Thank you for your remark.

**Comment by aryn832** [comment]
Update the silly README:

`GPU
GPU execution requires the following NVIDIA libraries to be installed:

[cuBLAS for CUDA 11](https://developer.nvidia.com/cublas)
[cuDNN 8 for CUDA 11](https://developer.nvidia.com/cudnn)`

**Comment by SeaDude** [comment]
To install CUDA 12 and use the latest `faster-whisper`, is it as simple as `pip install nvidia-cublas-cu12 nvidia-cudnn-cu12`?

**Comment by aryn832** [comment]
> To install CUDA 12 and use the latest `faster-whisper`, is it as simple as `pip install nvidia-cublas-cu12 nvidia-cudnn-cu12`?

it's actually insanely broken because it still requires cuDNN 11 but cuBLAS 12, just do a downgrade as @jhj0517 recommended.

**Comment by SeaDude** [comment]
I've been able to use the `-cu12` suffixes without issue.

**Comment by fedirz** [comment]
Here's a workaround, which might help for those trying to make it work in Docker.

https://github.com/SYSTRAN/faster-whisper/issues/516#issuecomment-2119010765

**Comment by MalikHaroonKhokhar** [comment]
install cuda 12 to resolve this issue : https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Debian&target_version=12&target_type=deb_local

**Comment by vanshnawander** [comment]
It doesn't work with cuda 13 as well. atleast it should have backward compatibility.

**Comment by side2k** [comment]
This helped to me, in my virtualenv:
1. Install libs(with active virtualenv):
```
pip install nvidia-cublas-cu12 nvidia-cudnn-cu12
```
2. Find the binaries:
```
$ find .venv -name 'libcublas*'
.venv/lib/python3.11/site-packages/nvidia/cublas/lib/libcublasLt.so.12
.venv/lib/python3.11/site-packages/nvidia/cublas/lib/libcublas.so.12
```
3. Add the `.venv/lib/python3.11/site-packages/nvidia/cublas/lib/` (path may be different in your virtualenv) to the `LD_LIBRARY_PATH`
```
export LD_LIBRARY_PATH=$VIRTUAL_ENV/lib/python3.11/site-packages/nvidia/cublas/lib/:$LD_LIBRARY_PATH
```

I have a strong suspision, that installing libs globally, not into a virtualenv, would make them available without messing with the `LD_LIBRARY_PATH` - I just assume all that above only needs to be done if you're using a virtualenv. 

P.S. quick one-liner test for wether Python in current env has access to `libcublas`:
```
echo "import ctypes;ctypes.CDLL('libcublas.so.12')"|python -
```
