### ISSUE TITLE
Cannot start faster-whisper

### ISSUE THREAD

**Issue by Denis-Kazakov** [SYSTRAN/faster-whisper#951]
I attempted to use faster-whisper in PyCharm, created a new project with dedicated venv and followed  the installation instructions given in this repo. However, when I tried to run the example script I got the following error message:
`Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory`
OS: Linux Mint

**Comment by tylerjthomas9** [comment]
We experienced this issue with torch v2.4. Downgrading to v2.3.1 fixed it for us.

**Comment by formater** [comment]
Denis, any update? Same issue here on Debian 12.
Cuda 12 installed, OpenAi`s whisper works, this one not :(

**Comment by Denis-Kazakov** [comment]
> We experienced this issue with torch v2.4. Downgrading to v2.3.1 fixed it for us.

Thanks. I checked torch version. It is already 2.3.1 in my case.

**Comment by Denis-Kazakov** [comment]
> Denis, any update? Same issue here on Debian 12. Cuda 12 installed, OpenAi`s whisper works, this one not :(

Alas no, I have given up on it. I am just a language researcher. 
I hope to be able to use "slower" Whisper for my application (online speech translation) through simpler logic. Another faster option is Vosk, but Whisper is better.

**Comment by Gldkslfmsd** [comment]
>  Note that LD_LIBRARY_PATH must be set before launching Python.

```
pip install nvidia-cublas-cu12 nvidia-cudnn-cu12

export LD_LIBRARY_PATH=`python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))'`
```

Did you see this in installation instructions? You need to do export LD_LIBRARY_PATH=... every time in the terminal where you are running faster-whisper.

**Comment by thomasmol** [comment]
> We experienced this issue with torch v2.4. Downgrading to v2.3.1 fixed it for us.

this fixed it for me as well!

**Comment by Denis-Kazakov** [comment]
> > Note that LD_LIBRARY_PATH must be set before launching Python.
> 
> ```
> pip install nvidia-cublas-cu12 nvidia-cudnn-cu12
> 
> export LD_LIBRARY_PATH=`python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))'`
> ```
> 
> Did you see this in installation instructions? You need to do export LD_LIBRARY_PATH=... every time in the terminal where you are running faster-whisper.

Hi! No, I did not see it and do not see it now at https://github.com/SYSTRAN/faster-whisper

Anyhow, I started PyCharm and ran this command in the terminal but got the same error.
![Screenshot_2024-08-22_00-00-33](https://github.com/user-attachments/assets/e68e0504-d7ad-49e1-9019-bdc1664cd8d6)
![Screenshot_2024-08-22_00-01-17](https://github.com/user-attachments/assets/c839ec50-665f-4528-b871-f67b9bbe9003)
